apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: myapp-build
spec:
  source:
    git:
      uri: https://github.com/torvicvasil1993/celery-test
    contextDir: /
  output:
    to:
      kind: ImageStreamTag
      name: myapp:latest
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3.9
      dockerfilePath: Dockerfile
#  triggers:
#    - type: GitHub
#      github:
#        secret: <your-github-webhook-secret>
#    - type: ConfigChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          env:
            - name: CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq:5672//
          command: ["celery"]
          args: ["-A", "myapp", "worker", "-B", "--loglevel=info"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080

