kind: ImageStream
apiVersion: v1
metadata:
  annotations:
    description: Keeps track of changes in the application image
  name: celery-worker-beat
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: celery-worker-beat-build
spec:
  source:
    git:
      uri: https://github.com/torvicvasil1993/celery-test
    contextDir: /
  output:
    to:
      kind: ImageStreamTag
      name: celery-worker-beat:latest
  strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
      postCommit: {}
#  triggers:
#    - type: GitHub
#      github:
#        secret: <your-github-webhook-secret>
#    - type: ConfigChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-beat
spec:
  selector:
    matchLabels:
      app: celery-worker-beat
  replicas: 1
  template:
    metadata:
      labels:
        app: celery-worker-beat
    spec:
      containers:
        - name: celery-worker-beat
          image: celery-worker-beat:latest
          env:
            - name: CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq:5672//
          command: ["celery"]
          args: ["-A", "myapp", "worker", "-B", "--loglevel=info"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: celery-worker-beat
spec:
  selector:
    app: celery-worker-beat
  ports:
    - name: http
      port: 8080
      targetPort: 8080

